# Generated by Django 3.0.3 on 2020-02-25 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200225_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='FusedResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoPath', models.CharField(default='~/', max_length=200)),
                ('videoName', models.CharField(default='a.mp4', max_length=100)),
                ('operationId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.VideoModel', verbose_name='operationId')),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoChunkPath', models.CharField(default='~/', max_length=200)),
                ('videoChunkName', models.CharField(default='1.mp4', max_length=100)),
                ('audioChunkPath', models.CharField(default='~/', max_length=200)),
                ('audioChunkName', models.CharField(default='1.mp3', max_length=200)),
                ('subtitleChunk', models.CharField(blank=True, default=' ', max_length=500)),
                ('timeInHours', models.IntegerField(default=0)),
                ('timeInMinutes', models.IntegerField(default=0)),
                ('timeInSeconds', models.IntegerField(default=0)),
                ('timeInMilliSeconds', models.IntegerField(default=0)),
                ('operationId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.VideoModel', verbose_name='operationId')),
            ],
        ),
    ]
