# Generated by Django 3.0.3 on 2020-03-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_fusedresult_videourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='me',
            field=models.IntegerField(default=0),
        ),
    ]
