# Generated by Django 3.0.4 on 2020-03-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_chunk_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='audioChunkLocalPath',
            field=models.CharField(default='1.mp3', max_length=100),
        ),
        migrations.AddField(
            model_name='chunk',
            name='videoChunkLocalPath',
            field=models.CharField(default='1.mp4', max_length=100),
        ),
    ]
