# Generated by Django 3.0.3 on 2020-02-25 05:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SrtModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srt', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/srts'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/videos'), upload_to='')),
            ],
        ),
    ]
