# Generated by Django 3.0.3 on 2020-02-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200225_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='srtmodel',
            name='path',
            field=models.CharField(default='~/', max_length=500),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='path',
            field=models.CharField(default='~/', max_length=500),
        ),
    ]
