# Generated by Django 3.0.3 on 2020-02-25 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200225_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='endTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
