# Generated by Django 3.0.3 on 2020-02-25 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chunk_endtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='re-uploads/')),
                ('path', models.CharField(default='~/', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='chunk',
            name='operationId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='rel', to='api.VideoModel', verbose_name='operationId'),
        ),
    ]
